[package]
name = "of-billing"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
otto-tenant.workspace = true
otto-resource.workspace = true
sqlx.workspace = true
serde.workspace = true
schemars.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["time", "sync", "rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
of-core.workspace = true
of-testkit.workspace = true
serde_json.workspace = true
